version: '3.8'

services:
  angular:
    image: ansalemocontainerregistry.azurecr.io/angular-frontend:latest
    ports:
      - "8080:8080"
    
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${AZURE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AZURE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AZURE_POSTGRES_DB}
    ports:
      - "5432:5432"
    
  node:
    image: ansalemocontainerregistry.azurecr.io/node-container:latest
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 60
