version: '3.8'

services:
  angular:
    container_name: angular-container
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - node
    
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment: 
      POSTGRES_USER: ${AZURE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AZURE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    
  node:
    container_name: node-container
    build: ./../server/
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 60
    depends_on: 
      - postgres
  
