version: '3.8'

services:
  angular:
    container_name: angular-container
    build: .
    ports:
      - "8080:8080"
    links:
      - node
  
  postgres:
    image: postgres:latest
    env_file: "./../server/.env"
    
  node:
    container_name: node-container
    build: ./../server/
    ports:
      - "3000:3000"
